FROM node:latest

# Copy a local file when building the image:
#COPY ./timezone /etc/timezone
RUN mkdir /app
WORKDIR /app

# The command to run when the container starts (default for this image would be fine too):
COPY package.json /app
RUN npm install

# Bundle app source
COPY . /app
RUN ls

